# Site Settings
title: Blog prawniczy — Edyta Kuś
tagline: O prawie, w prawie, w ramach prawa
email: kontakt@edytakus.pl
description: >
  Blog adwokatki z Wrocławia. W każdą środę i piątek umieszczam wpis starający się możliwie ludzkim językiem wyjaśniać codzienne problemy prawne.
# baseurl: "/blog"
url: "https://edytakus.pl"
permalink: pretty
default_locale: "pl"
twitter_username: adwokat_ek

paginate: 8
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  shortname: adwokatek

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-timeago

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-178496414-1

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Edyta Kuś"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu



collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  articles:
    sort_by: sok
    output: true
    layout: article
    image: https://via.placeholder.com/800x600
    show_sidebar: false
    hide_hero: true

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

jekyll_timeago:
  depth: 2
  translations_path: '/locales/*.yml'
  available_locales:
    - 'ru'
    - 'pl'
  default_locale: 'ru'
  fallbacks: true
